### PR TITLE
This commit make changes to many spec names

### PR DESCRIPTION
**Pull request by Sedward**
This is a cleaned up branch that should not contain merge conflicts. We should be able to close the previous PR.

### CODE REVIEW

**Comment by gsemet** [comment]
it only contains 1 change ? how does it behave with prefix?

**Comment by Sedward** [comment]
I went back an created a new branch and cherry picked my changes onto it. It could be that all the changes are already in. I was getting some bad merge conflicts due to the history not adding up. I should have been branching off your helm_chart branch but I didn't know at the time so I had a bad history. From here on forwards I should branch of of that and then I will be able to rebase my changes.

**Review by gsemet — CHANGES_REQUESTED** [review]
I don’t see the point of just replacing these name

**Comment by gsemet** [comment]
please reupdate your change or adapt it. My only requirement here is to keep the prefix thing somehow

**Pull request closed without merging**
